name: Simple CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Use 'temurin' for the OpenJDK 
          java-version: '17'

      - name: Set up Maven
        uses: actions/setup-java@v3
        with:
          maven-version: '3.8.1'
          java-version: '17'

      - name: Build and Run Tests
        run: mvn clean package
