name: Simple CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Use 'temurin' for the OpenJDK distribution
          java-version: '17'


      - name: Install Maven
        run: |
            wget https://downloads.apache.org/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.tar.gz
            tar -xvzf apache-maven-3.8.6-bin.tar.gz
            mv apache-maven-3.8.6 /opt/maven
            echo "M2_HOME=/opt/maven" >> $GITHUB_ENV
            echo "MAVEN_HOME=/opt/maven" >> $GITHUB_ENV
            echo "/opt/maven/bin" >> $GITHUB_PATH
  
      - name: Verify Maven Version
        run: mvn -version
  
      - name: Build and Test with Maven
        run: mvn clean install
